title: digital diary
tagline:   " music and rhythm find their way into the secret places of the soul " 

# custom styles:
sass:
  sass_dir: assets/css/style.css

include:
  - assets

collections:
  gallery:
    output: true
  fragments:
    output: true
  fieldnotes:
    output: true
