# custom styles:
sass:
  sass_dir: assets/css/style.css

include:
  - assets

collections:
  gallery:
    output: true
  fragments:
    output: true
  fieldnotes:
    output: true

nav:
  - title: Gallery
    url: /gallery
  - title: Fragments
    url: /fragments
  - title: Field Notes
    url: /fieldnotes
