theme: jekyll-theme-midnight
markdown: kramdown
# custom styles:
sass:
  sass_dir: assets/css
  
collections:
  gallery:
    output: true
  fragments:
    output: true
  fieldnotes:
    output: true

include:
  - assets
  - _gallery
  - _fragments
  - _fieldnotes
  - _layouts
  - _includes

nav:
  - title: Gallery
    url: /gallery
  - title: Fragments
    url: /fragments
  - title: Field Notes
    url: /fieldnotes
